name: Build and publish (branch/docs)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours (UTC)

permissions:
  contents: write  # we push updated data and docs

jobs:
  build_docs_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests pandas matplotlib

      - name: Run fetcher (append JSONL)
        run: python WienMobilFetchProcessStore.py

      - name: Run visualizer (create PNG)
        run: python Visualization.py

      - name: Prepare /docs website
        run: |
          mkdir -p docs
          # chart image from your visualizer
          cp data/total_bikes_over_time.png docs/
          # disable Jekyll so Pages serves plain files
          touch docs/.nojekyll
          # simple index that shows the chart
          BUILD_TIME="$(date -u +'%Y-%m-%d %H:%M:%SZ')"
          cat > docs/index.html << HTML
          <!doctype html>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <title>WienMobil Bikes — Total over time</title>
          <style>
            body { font-family: system-ui,-apple-system,Segoe UI,Roboto,sans-serif; padding: 1rem; }
            figure { max-width: 1100px; margin: 0 auto; }
            img { width: 100%; height: auto; border: 1px solid #ddd; }
            .meta { color:#555; font-size:.9rem; margin:.5rem 0 1rem; }
          </style>
          <h1>WienMobil Bikes — Total bikes available</h1>
          <p class="meta">Updated by GitHub Actions. Build (UTC): ${BUILD_TIME}. Times on chart: Europe/Vienna.</p>
          <figure>
            <img src="total_bikes_over_time.png" alt="Total bikes over time">
            <figcaption>City-wide total per snapshot (hourly).</figcaption>
          </figure>
          HTML
          echo "Files in docs/:"
          ls -la docs

      - name: Commit updated data & docs (if changed)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/bikeshare.jsonl docs/index.html docs/total_bikes_over_time.png docs/.nojekyll || true
          if ! git diff --cached --quiet; then
            git commit -m "Update data & docs [skip ci]"
            git push
          else
            echo "Nothing to commit."
          fi
